//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public System.Guid Id { get; set; }
        public string Answer { get; set; }
        public bool Right { get; set; }
        public System.Guid QuestionId { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
